version: '3'
services:
  identity-server-build:
    build: src/Be.Vlaanderen.Basisregisters.IdentityServer/
    environment:
      - IdentityServer__ConfigFolder=/home/identityserver/example-config
    ports:
      - "5050:80"
