name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency: CI
jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Build and publish image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha_short.outputs.sha_short }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}

    - name: .NET version
      shell: bash
      run: dotnet --info

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set outputs
      id: sha_short
      run: echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./src/Be.Vlaanderen.Basisregisters.IdentityServer
        push: true
        tags: ghcr.io/informatievlaanderen/identity-server-fake:${{ steps.sha_short.outputs.sha_short }}, ghcr.io/informatievlaanderen/identity-server-fake:latest

  test:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Run identity server fake container
        shell: bash
        run: |
          docker run -d --name acm -p 5050:80 -v ${{ github.workspace }}/example-config:/home/identityserver ghcr.io/informatievlaanderen/identity-server-fake:${{ needs.build.outputs.sha_short }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ secrets.VBR_DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Shows logs identity server fake container
        if: ${{ always() }}
        shell: bash
        run: |
          docker logs acm
